# Generated by Django 5.1.6 on 2025-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_drinktype_remove_order_beverage_remove_order_pizza_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinktype',
            name='double',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinktype',
            name='simple',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
