# Generated by Django 5.1.6 on 2025-03-16 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_drinktype_double_drinktype_simple'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
