# Generated by Django 5.1.6 on 2025-03-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinktype',
            old_name='name',
            new_name='drink_type',
        ),
        migrations.RemoveField(
            model_name='drinktype',
            name='description',
        ),
    ]
